CREATE TABLE IF NOT EXISTS popup (
  id SERIAL PRIMARY KEY,
  "imageUrl" VARCHAR NOT NULL,
  "linkUrl" VARCHAR,
  "startDate" TIMESTAMP NOT NULL,
  "endDate" TIMESTAMP NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);
