CREATE TABLE IF NOT EXISTS network (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  "logoUrl" VARCHAR,
  "darkBg" BOOLEAN NOT NULL DEFAULT FALSE,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS partner (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  "logoUrl" VARCHAR,
  "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);
